# Generated by Django 3.2.7 on 2021-10-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pethomeApp', '0002_auto_20211005_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='state',
        ),
        migrations.AddField(
            model_name='pet',
            name='avaliable',
            field=models.BooleanField(default=True, verbose_name='avaliable'),
        ),
    ]
