# Generated by Django 3.2.7 on 2021-10-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pethomeApp', '0004_auto_20211012_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='bday_aprox',
            field=models.DateField(verbose_name='bday_aprox'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='date_register',
            field=models.DateField(verbose_name='date_register'),
        ),
    ]
